# -*- coding: utf-8 -*-
"""bibi amna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fgz7X4MFIK9IhGeK5Mz1p7Hp-oR5-5X
"""

# Function to calculate BMI
def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    return bmi

# Function to determine BMI category
def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25:
        return "Healthy"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"

# Function to calculate daily water intake
def water_intake(weight):
    return weight * 0.03  # liters

# Function to display final report
def display_report(name, bmi, category, water):
    print("\n====== MEMBER HEALTH REPORT ======")
    print("Name:", name)
    print("BMI:", round(bmi, 2))
    print("BMI Category:", category)
    print("Daily Water Intake:", round(water, 2), "liters")
    print("=================================\n")

# Main program loop
while True:
    choice = input("Press Enter to add a new member or type 'q' to exit: ").lower()

    if choice == 'q':
        break

    # Taking member details
    name = input("Enter member name: ")
    weight = float(input("Enter weight in kg: "))
    height = float(input("Enter height in meters: "))

    # Calculations
    bmi = calculate_bmi(weight, height)
    category = bmi_category(bmi)
    water = water_intake(weight)

    # Display result
    display_report(name, bmi, category, water)

# Exit message
print("\nThank you for using the Fitness Center Health Tool 💪")



