# -*- coding: utf-8 -*-
"""cinezone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sl7t32uEUUOc0289oxCbNCRXNbML8QCP
"""

# Welcome Message
print("======================================================")
print("     Welcome to CineZone Online Booking System")
print("======================================================\n")

# Movie List
print("Now Showing:")
print("------------------------------------------------------")
print("1. Inside Out 2          | 12:30 PM")
print("2. Venom 3               | 03:00 PM")
print("3. Joker 2               | 06:30 PM")
print("4. Kung Fu Panda 4       | 09:00 PM")
print("------------------------------------------------------\n")

# Customer Name
customer_name = input("Please enter your name: ")

# Movie Selection
choice = int(input("Enter the movie number you want to watch: "))

# Movie Mapping
if choice == 1:
    movie_name = "Inside Out 2"
    show_time = "12:30 PM"
elif choice == 2:
    movie_name = "Venom 3"
    show_time = "03:00 PM"
elif choice == 3:
    movie_name = "Joker 2"
    show_time = "06:30 PM"
elif choice == 4:
    movie_name = "Kung Fu Panda 4"
    show_time = "09:00 PM"
else:
    print("Invalid choice! Please restart the program.")
    exit()

# Tickets
tickets = int(input(f"How many tickets would you like to buy for {movie_name}? "))

# Prices
ticket_price = 500
snack_price = 300

# Snacks
snack_choice = input("Do you want to add a popcorn combo (Rs. 300 each)? Type yes or no: ").lower()

if snack_choice == "yes":
    snack_total = tickets * snack_price
    snack_text = "Yes"
else:
    snack_total = 0
    snack_text = "No"

# Offer Calculation
free_tickets = tickets // 4
payable_tickets = tickets - free_tickets

# Cost Calculation
ticket_total = payable_tickets * ticket_price
final_bill = ticket_total + snack_total

# Receipt
print("\n-----------------------------------------------------------------------------------")
print("               CINEZONE CINEMA BOOKING")
print("-----------------------------------------------------------------------------------")
print(f"Customer Name: {customer_name}")
print(f"Movie Selected: {movie_name}")
print(f"Showtime: {show_time}\n")

print(f"Tickets Purchased: {tickets}")
print(f"Free Tickets: {free_tickets}")
print(f"Tickets Charged: {payable_tickets}")
print(f"Ticket Price (each): Rs.{ticket_price}")
print(f"Snack Combo: {snack_text}")
print(f"Snack Combo Total: Rs.{snack_total}\n")

print("-----------------------------------------------------------------------------------")
print(f"Total Amount Payable: Rs.{final_bill}")
print("-----------------------------------------------------------------------------------")
print("Thank you for booking with CineZone Cinema!")
print("Enjoy your movie!")
print("-----------------------------------------------------------------------------------")