# -*- coding: utf-8 -*-
"""student  grading system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLYk9qOAMZlClq1_md3qa6VKjqSdGD_D
"""

# Ask student name
student_name = input("Enter student name: ")

# Ask how many subjects
num_subjects = int(input(" Enter number of subject"))

total_marks = 0

# Lists to store subjects and marks
subjects = []
marks_list = []

# appling for loop  for taking subject name and marks
for i in range(1, num_subjects + 1):
    subject_name = input(f"Enter name of subject {i}: ")
    marks = float(input(f"Enter marks of {subject_name}: "))

    subjects.append(subject_name)
    marks_list.append(marks)

    total_marks += marks

# Calculations
average_marks = total_marks / num_subjects
percentage = (total_marks / (num_subjects * 100)) * 100

# Result and grade
if percentage >= 50:
    result = "PASS"

    # Nested if for grade
    if percentage >= 90:
        grade = "A+"
    elif percentage >= 80:
        grade = "A"
    elif percentage >= 70:
        grade = "B"
    elif percentage >= 60:
        grade = "C"
    else:
        grade = "D"
else:
    result = "FAIL"
    grade = "No Grade"

# Printing final report
print("\n========== STUDENT REPORT ==========")
print(f"Student Name : {student_name}")
print("\nSubjects and Marks:")
for i in range(num_subjects):
    print(f"{subjects[i]} : {marks_list[i]}")

print("\nTotal Marks :", total_marks)
print("Average Marks :", average_marks)
print("Percentage :", percentage)
print("Result :", result)
print("Grade :", grade)
print("===================================")













